artifact_location: file:///home/runner/work/Loan-Default-Prediction-Model/Loan-Default-Prediction-Model/mlruns/862911887950428294
creation_time: 1773128385723
experiment_id: '862911887950428294'
last_update_time: 1773128385723
lifecycle_stage: active
name: Loan_Default_Project
