name: Train Model

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training script
        run: python train.py

      - name: Commit trained model
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/best_params.json
          git add data/schema.json
          git add models/loan_pred_model_v1.joblib
          git add data/performance_metrics.csv
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-trained model update"
          git push
