name: Train ML Model

on:
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Training Pipeline
        run: python main.py

      - name: Commit Model Updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add models/loan_pred_model_v1.joblib
          git add artifacts/schema.json
          git add artifacts/best_params.json
          git add artifacts/confusion_matrix.png
          git commit -m "Automated model retraining update [skip ci]" || echo "No changes"
          git push
    
      - name: Upload MLflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-results
          path: mlruns
